SELECT YEAR(T2.SALES_DATE) AS YEAR, MONTH(T2.SALES_DATE) AS MONTH, T1.GENDER, COUNT(DISTINCT T1.USER_ID) AS USERS
FROM USER_INFO T1 JOIN ONLINE_SALE T2 ON T1.USER_ID = T2.USER_ID
WHERE T1.GENDER IS NOT NULL
GROUP BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE), T1.GENDER
ORDER BY YEAR, MONTH, GENDER
