SELECT T1.ID, COALESCE(T2.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA T1 LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS T2
ON T1.ID = T2.PARENT_ID
ORDER BY T1.ID
