SELECT T1.ID, T2.FISH_NAME, T1.LENGTH AS LENGTH
FROM FISH_INFO T1 JOIN FISH_NAME_INFO T2 ON T1.FISH_TYPE = T2.FISH_TYPE
WHERE T1.FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY T1.ID ASC
