SELECT T1.ITEM_ID, T1.ITEM_NAME, T1.RARITY
FROM ITEM_INFO T1
WHERE T1.ITEM_ID NOT IN (
    SELECT T2.PARENT_ITEM_ID
    FROM ITEM_TREE T2
    WHERE T2.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY T1.ITEM_ID DESC
