SELECT 
    T2.HISTORY_ID, 
    ROUND(
        T1.DAILY_FEE * (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) *
        (100 - IFNULL(T3.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR T1
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2 
    ON T1.CAR_ID = T2.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
    ON T1.CAR_TYPE = T3.CAR_TYPE
   AND (
        (T3.DURATION_TYPE = '90일 이상' AND (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) >= 90)
     OR (T3.DURATION_TYPE = '30일 이상' AND (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) >= 30 
                                       AND (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) < 90)
     OR (T3.DURATION_TYPE = '7일 이상'  AND (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) >= 7  
                                       AND (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) < 30)
   )
WHERE T1.CAR_TYPE = '트럭'
ORDER BY FEE DESC, T2.HISTORY_ID DESC;
