SELECT DISTINCT T1.USER_ID, T1.PRODUCT_ID
FROM ONLINE_SALE T1, ONLINE_SALE T2 
WHERE T1.USER_ID = T2.USER_ID AND T1.PRODUCT_ID = T2.PRODUCT_ID AND T1.SALES_DATE <> T2.SALES_DATE
ORDER BY T1.USER_ID ASC, T1.PRODUCT_ID DESC;
