SELECT T2.AUTHOR_ID,
        T2.AUTHOR_NAME,
        T1.CATEGORY,
        SUM(T1.PRICE * T3.SALES) AS TOTAL_SALES
FROM BOOK T1 
INNER JOIN AUTHOR T2 ON T1.AUTHOR_ID = T2.AUTHOR_ID
INNER JOIN BOOK_SALES T3 ON T1.BOOK_ID = T3.BOOK_ID
WHERE YEAR(T3.SALES_DATE) = 2022 AND MONTH(T3.SALES_DATE) = 01 
GROUP BY T2.AUTHOR_NAME, T1.CATEGORY
ORDER BY T2.AUTHOR_ID ASC, T1.CATEGORY DESC
