SELECT DISTINCT T2.USER_ID, 
        T2.NICKNAME, 
        CONCAT(T2.CITY, ' ', T2.STREET_ADDRESS1, ' ', T2.STREET_ADDRESS2) AS '전체주소', 
        CONCAT(SUBSTRING(T2.TLNO, 1, 3), '-', SUBSTRING(T2.TLNO, 4, 4), '-', SUBSTRING(T2.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD T1 JOIN USED_GOODS_USER T2 ON T1.WRITER_ID = T2.USER_ID
WHERE T1.WRITER_ID IN (SELECT WRITER_ID
                    FROM USED_GOODS_BOARD T3
                    GROUP BY WRITER_ID 
                    HAVING COUNT(*) >= 3)
ORDER BY T2.USER_ID DESC
